# Generated by Django 4.1.13 on 2024-09-25 02:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_documento_usuario', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de extranjería', 'Cédula de extranjería')], db_column='tipo_documento_usuario', default='Cedula de ciudadania', max_length=50)),
                ('numero_documento_usuario', models.CharField(db_column='numero_documento_usuario', max_length=20, unique=True)),
                ('genero_usuario', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_usuario', max_length=9)),
                ('rol_usuario', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Guardia de seguridad', 'Guardia de seguridad'), ('Usuario', 'Usuario')], db_column='rol_usuario', default='Usuario', max_length=20)),
                ('face_register', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(db_column='nombre_oficina', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(db_column='nombre_programa', max_length=100)),
                ('tipo_formacion_programa', models.CharField(choices=[('Tecnólogo', 'Tecnólogo'), ('Técnico', 'Técnico')], db_column='tipo_formacion_programa', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(db_column='nombre_tutor', max_length=50)),
                ('apellido_tutor', models.CharField(db_column='apellido_tutor', max_length=50)),
                ('tipo_documento_tutor', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Cédula de extranjería', 'Cédula de extranjería')], db_column='tipo_documento_tutor', default='Cedula de ciudadania', max_length=50)),
                ('numero_documento_tutor', models.CharField(db_column='numero_documento_tutor', max_length=20, unique=True)),
                ('celular_tutor', models.CharField(db_column='celular_tutor', max_length=12)),
                ('genero_tutor', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_tutor', max_length=20)),
                ('parentezco_tutor', models.CharField(db_column='parentezco_tutor', max_length=30)),
                ('usuario_tutor', models.ForeignKey(db_column='usuario_tutor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biometricos_registro', models.ImageField(db_column='datos_biometricos_registro', upload_to='datos_biometricos_registro')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_registro')),
                ('usuario_registro_facial', models.ForeignKey(db_column='usuario_registro_facial', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_objeto', models.CharField(db_column='marca_objeto', max_length=20)),
                ('modelo_objeto', models.CharField(db_column='modelo_objeto', max_length=20)),
                ('descripcion_objeto', models.TextField(db_column='descripcion_objeto')),
                ('foto_objeto', models.URLField(blank=True, db_column='foto_objeto', max_length=300, null=True)),
                ('usuario_objeto', models.ForeignKey(db_column='usuario_objeto', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biometricos_ingreso', models.ImageField(db_column='datos_biometricos_ingreso', upload_to='datos_biometricos_ingreso')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_ingreso')),
                ('usuario_ingreso', models.ForeignKey(db_column='usuario_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(db_column='numero_ficha', max_length=20, unique=True)),
                ('aprendices_matriculados_ficha', models.IntegerField(db_column='aprendices_matriculados_ficha')),
                ('aprendices_actuales_ficha', models.IntegerField(db_column='aprendices_actuales_ficha')),
                ('jornada_ficha', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='jornada_ficha', max_length=50)),
                ('programa_ficha', models.ForeignKey(db_column='programa_ficha', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
