# Generated by Django 4.1.13 on 2024-09-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='face_register',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(blank=True, db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_usuario', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(blank=True, choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Guardia de seguridad', 'Guardia de seguridad'), ('Usuario', 'Usuario')], db_column='rol_usuario', default='Usuario', max_length=20, null=True),
        ),
    ]
