# Generated by Django 4.1.13 on 2024-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0002_alter_usuario_face_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(blank=True, choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Guardia de seguridad', 'Guardia de seguridad'), ('Usuario', 'Usuario')], db_column='rol_usuario', max_length=20, null=True),
        ),
    ]
