# Generated by Django 4.1.13 on 2024-09-18 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0004_tutor_alter_ficha_programa_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='programa_ficha',
            field=models.ForeignKey(db_column='programa_ficha', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='usuario_ingreso',
            field=models.ForeignKey(db_column='usuario_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='usuario_objeto',
            field=models.ForeignKey(db_column='usuario_objeto', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo_formacion_programa',
            field=models.CharField(choices=[('Tecnólogo', 'Tecnólogo'), ('Técnico', 'Técnico')], db_column='tipo_formacion_programa', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrofacial',
            name='usuario_registro_facial',
            field=models.ForeignKey(db_column='usuario_registro_facial', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tipo_documento_tutor',
            field=models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Cédula de extranjería', 'Cédula de extranjería')], db_column='tipo_documento_tutor', default='Cedula de ciudadania', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='usuario_tutor',
            field=models.ForeignKey(db_column='usuario_tutor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Guardia de seguridad', 'Guardia de seguridad'), ('Usuario', 'Usuario')], db_column='rol_usuario', default='Usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_usuario',
            field=models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de extranjería', 'Cédula de extranjería')], db_column='tipo_documento_usuario', default='Cedula de ciudadania', max_length=50),
        ),
    ]
