# Generated by Django 4.1.13 on 2024-08-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0004_tutor_alter_ficha_programa_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='programa_ficha',
            field=models.ForeignKey(db_column='programa_ficha', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='usuario_ingreso',
            field=models.ForeignKey(db_column='usuario_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='usuario_objeto',
            field=models.ForeignKey(db_column='usuario_objeto', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrofacial',
            name='usuario_registro_facial',
            field=models.ForeignKey(db_column='usuario_registro_facial', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='usuario_tutor',
            field=models.ForeignKey(db_column='usuario_tutor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
    ]
